version: '2'
services:
  nginx-proxy:
    image: jlesage/nginx-proxy-manager
    restart: always
    ports:
      - "81:8181"
      - "80:8080"
#    volumes:
#      - "/root/nginx-proxy-manager:/config:rw"
    networks:
      - localnet

networks:
  localnet:
    external:
      name: localnet

